postgresqldrone:
  image: sameersbn/postgresql:9.1-1
  environment:
   - DB_USER=drone
   - DB_PASS=6ifL!fe
   - DB_NAME=drone
drone:
  image: jdye/drone:latest
  environment:
   - DRONE_SERVER_PORT=80
  external_links:
   - gitlab
  links:
   - postgresqldrone:postgresql
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - drone.toml.tmpl:/etc/drone/drone.toml.tmpl
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  ports:
   - "20080:80"
  privileged: true

# vim: set ts=2 sw=2 expandtab:
